window.IPAS_DATA = {
  "updated_at": "28 Aug 2026, 11:00:00 (Sync 28 Agustus)",
  "se_umum": [
    {
      "kabupaten": "[01] BANGGAI KEPULAUAN",
      "total_prelist": 59563,
      "total_draft": 1764,
      "total_open": 652,
      "total_submitted": 54962,
      "total_rejected": 2051,
      "total_approved": 43898,
      "total_submitted_pencacah": 10250,
      "total_submitted_respondent": 13,
      "persentase": 92.28,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 5471,
          "total_draft": 129,
          "total_open": 20,
          "total_submitted": 5174,
          "total_rejected": 140,
          "total_approved": 4031,
          "total_submitted_pencacah": 968,
          "total_submitted_respondent": 1,
          "persentase": 94.57,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 4004,
          "total_draft": 263,
          "total_open": 40,
          "total_submitted": 3255,
          "total_rejected": 435,
          "total_approved": 2557,
          "total_submitted_pencacah": 621,
          "total_submitted_respondent": 0,
          "persentase": 81.29,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 10525,
          "total_draft": 451,
          "total_open": 397,
          "total_submitted": 9392,
          "total_rejected": 252,
          "total_approved": 6618,
          "total_submitted_pencacah": 2718,
          "total_submitted_respondent": 6,
          "persentase": 89.24,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 3718,
          "total_draft": 401,
          "total_open": 2,
          "total_submitted": 2853,
          "total_rejected": 430,
          "total_approved": 1766,
          "total_submitted_pencacah": 1081,
          "total_submitted_respondent": 0,
          "persentase": 76.73,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[042] SIDOAN",
          "kec_name": "[042] SIDOAN",
          "total_prelist": 4234,
          "total_draft": 38,
          "total_open": 8,
          "total_submitted": 3923,
          "total_rejected": 260,
          "total_approved": 2655,
          "total_submitted_pencacah": 1247,
          "total_submitted_respondent": 0,
          "persentase": 92.65,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 4639,
          "total_draft": 6,
          "total_open": 0,
          "total_submitted": 4483,
          "total_rejected": 147,
          "total_approved": 3575,
          "total_submitted_pencacah": 868,
          "total_submitted_respondent": 1,
          "persentase": 96.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 4582,
          "total_draft": 3,
          "total_open": 5,
          "total_submitted": 4403,
          "total_rejected": 162,
          "total_approved": 4156,
          "total_submitted_pencacah": 129,
          "total_submitted_respondent": 1,
          "persentase": 96.09,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 4808,
          "total_draft": 22,
          "total_open": 0,
          "total_submitted": 4774,
          "total_rejected": 8,
          "total_approved": 4484,
          "total_submitted_pencacah": 231,
          "total_submitted_respondent": 0,
          "persentase": 99.29,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[061] BATUDAKA",
          "kec_name": "[061] BATUDAKA",
          "total_prelist": 4610,
          "total_draft": 111,
          "total_open": 41,
          "total_submitted": 4438,
          "total_rejected": 10,
          "total_approved": 3929,
          "total_submitted_pencacah": 424,
          "total_submitted_respondent": 0,
          "persentase": 96.27,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[062] TAOPA",
          "kec_name": "[062] TAOPA",
          "total_prelist": 4189,
          "total_draft": 43,
          "total_open": 21,
          "total_submitted": 4084,
          "total_rejected": 35,
          "total_approved": 3584,
          "total_submitted_pencacah": 379,
          "total_submitted_respondent": 2,
          "persentase": 97.49,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 4683,
          "total_draft": 258,
          "total_open": 65,
          "total_submitted": 4215,
          "total_rejected": 141,
          "total_approved": 3004,
          "total_submitted_pencacah": 1194,
          "total_submitted_respondent": 2,
          "persentase": 90.01,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[071] POSO KOTA UTARA",
          "kec_name": "[071] POSO KOTA UTARA",
          "total_prelist": 4100,
          "total_draft": 39,
          "total_open": 53,
          "total_submitted": 3968,
          "total_rejected": 31,
          "total_approved": 3539,
          "total_submitted_pencacah": 390,
          "total_submitted_respondent": 0,
          "persentase": 96.78,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[02] BANGGAI",
      "total_prelist": 180552,
      "total_draft": 6624,
      "total_open": 7275,
      "total_submitted": 155173,
      "total_rejected": 11179,
      "total_approved": 86528,
      "total_submitted_pencacah": 68022,
      "total_submitted_respondent": 8,
      "persentase": 85.94,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 10126,
          "total_draft": 248,
          "total_open": 491,
          "total_submitted": 9054,
          "total_rejected": 328,
          "total_approved": 6620,
          "total_submitted_pencacah": 2374,
          "total_submitted_respondent": 2,
          "persentase": 89.41,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 10484,
          "total_draft": 120,
          "total_open": 0,
          "total_submitted": 10080,
          "total_rejected": 264,
          "total_approved": 6910,
          "total_submitted_pencacah": 3121,
          "total_submitted_respondent": 0,
          "persentase": 96.15,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[012] ULUJADI",
          "kec_name": "[012] ULUJADI",
          "total_prelist": 8595,
          "total_draft": 265,
          "total_open": 515,
          "total_submitted": 7719,
          "total_rejected": 91,
          "total_approved": 5939,
          "total_submitted_pencacah": 1757,
          "total_submitted_respondent": 0,
          "persentase": 89.81,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[013] TOILI JAYA",
          "kec_name": "[013] TOILI JAYA",
          "total_prelist": 7182,
          "total_draft": 135,
          "total_open": 47,
          "total_submitted": 6927,
          "total_rejected": 7,
          "total_approved": 4771,
          "total_submitted_pencacah": 2066,
          "total_submitted_respondent": 0,
          "persentase": 96.45,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 8156,
          "total_draft": 988,
          "total_open": 579,
          "total_submitted": 6500,
          "total_rejected": 77,
          "total_approved": 3946,
          "total_submitted_pencacah": 2528,
          "total_submitted_respondent": 0,
          "persentase": 79.7,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[021] PARIGI SELATAN",
          "kec_name": "[021] PARIGI SELATAN",
          "total_prelist": 6658,
          "total_draft": 64,
          "total_open": 325,
          "total_submitted": 5981,
          "total_rejected": 282,
          "total_approved": 3136,
          "total_submitted_pencacah": 2828,
          "total_submitted_respondent": 0,
          "persentase": 89.83,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 9508,
          "total_draft": 1467,
          "total_open": 102,
          "total_submitted": 6780,
          "total_rejected": 1159,
          "total_approved": 2413,
          "total_submitted_pencacah": 4357,
          "total_submitted_respondent": 0,
          "persentase": 71.31,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 8129,
          "total_draft": 210,
          "total_open": 256,
          "total_submitted": 6522,
          "total_rejected": 1136,
          "total_approved": 2258,
          "total_submitted_pencacah": 4255,
          "total_submitted_respondent": 0,
          "persentase": 80.23,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[032] TORIBULU",
          "kec_name": "[032] TORIBULU",
          "total_prelist": 7341,
          "total_draft": 50,
          "total_open": 2,
          "total_submitted": 7210,
          "total_rejected": 51,
          "total_approved": 3646,
          "total_submitted_pencacah": 3524,
          "total_submitted_respondent": 0,
          "persentase": 98.22,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 5317,
          "total_draft": 100,
          "total_open": 22,
          "total_submitted": 5078,
          "total_rejected": 109,
          "total_approved": 2552,
          "total_submitted_pencacah": 2483,
          "total_submitted_respondent": 0,
          "persentase": 95.5,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 20198,
          "total_draft": 813,
          "total_open": 1248,
          "total_submitted": 16870,
          "total_rejected": 1236,
          "total_approved": 6211,
          "total_submitted_pencacah": 10646,
          "total_submitted_respondent": 4,
          "persentase": 83.52,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 5881,
          "total_draft": 147,
          "total_open": 42,
          "total_submitted": 5475,
          "total_rejected": 213,
          "total_approved": 2468,
          "total_submitted_pencacah": 2999,
          "total_submitted_respondent": 0,
          "persentase": 93.1,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[052] PALASA",
          "kec_name": "[052] PALASA",
          "total_prelist": 10530,
          "total_draft": 273,
          "total_open": 585,
          "total_submitted": 9208,
          "total_rejected": 461,
          "total_approved": 4056,
          "total_submitted_pencacah": 5149,
          "total_submitted_respondent": 0,
          "persentase": 87.45,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[053] LUWUK SELATAN",
          "kec_name": "[053] LUWUK SELATAN",
          "total_prelist": 15781,
          "total_draft": 890,
          "total_open": 1789,
          "total_submitted": 12530,
          "total_rejected": 557,
          "total_approved": 7337,
          "total_submitted_pencacah": 5144,
          "total_submitted_respondent": 2,
          "persentase": 79.4,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[054] NAMBO",
          "kec_name": "[054] NAMBO",
          "total_prelist": 5388,
          "total_draft": 9,
          "total_open": 1,
          "total_submitted": 4928,
          "total_rejected": 445,
          "total_approved": 1309,
          "total_submitted_pencacah": 3574,
          "total_submitted_respondent": 0,
          "persentase": 91.46,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 10780,
          "total_draft": 512,
          "total_open": 1122,
          "total_submitted": 8670,
          "total_rejected": 449,
          "total_approved": 3824,
          "total_submitted_pencacah": 4826,
          "total_submitted_respondent": 0,
          "persentase": 80.43,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[061] BATUDAKA",
          "kec_name": "[061] BATUDAKA",
          "total_prelist": 8453,
          "total_draft": 29,
          "total_open": 0,
          "total_submitted": 8222,
          "total_rejected": 194,
          "total_approved": 7722,
          "total_submitted_pencacah": 493,
          "total_submitted_respondent": 0,
          "persentase": 97.27,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[062] TAOPA",
          "kec_name": "[062] TAOPA",
          "total_prelist": 1730,
          "total_draft": 13,
          "total_open": 105,
          "total_submitted": 1515,
          "total_rejected": 93,
          "total_approved": 696,
          "total_submitted_pencacah": 805,
          "total_submitted_respondent": 0,
          "persentase": 87.57,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 3034,
          "total_draft": 7,
          "total_open": 21,
          "total_submitted": 2990,
          "total_rejected": 11,
          "total_approved": 2208,
          "total_submitted_pencacah": 740,
          "total_submitted_respondent": 0,
          "persentase": 98.55,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[071] POSO KOTA UTARA",
          "kec_name": "[071] POSO KOTA UTARA",
          "total_prelist": 5979,
          "total_draft": 276,
          "total_open": 23,
          "total_submitted": 4326,
          "total_rejected": 1349,
          "total_approved": 3465,
          "total_submitted_pencacah": 843,
          "total_submitted_respondent": 0,
          "persentase": 72.35,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[072] POSO KOTA SELATAN",
          "kec_name": "[072] POSO KOTA SELATAN",
          "total_prelist": 3249,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 2498,
          "total_rejected": 746,
          "total_approved": 888,
          "total_submitted_pencacah": 1604,
          "total_submitted_respondent": 0,
          "persentase": 76.89,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[080] SOYO JAYA",
          "kec_name": "[080] SOYO JAYA",
          "total_prelist": 3339,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 2801,
          "total_rejected": 507,
          "total_approved": 2431,
          "total_submitted_pencacah": 346,
          "total_submitted_respondent": 0,
          "persentase": 83.89,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[081] WALEA BESAR",
          "kec_name": "[081] WALEA BESAR",
          "total_prelist": 2470,
          "total_draft": 7,
          "total_open": 0,
          "total_submitted": 1375,
          "total_rejected": 1086,
          "total_approved": 630,
          "total_submitted_pencacah": 744,
          "total_submitted_respondent": 0,
          "persentase": 55.67,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[082] TALATAKO",
          "kec_name": "[082] TALATAKO",
          "total_prelist": 2244,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 1914,
          "total_rejected": 328,
          "total_approved": 1092,
          "total_submitted_pencacah": 816,
          "total_submitted_respondent": 0,
          "persentase": 85.29,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[03] MOROWALI",
      "total_prelist": 77070,
      "total_draft": 4106,
      "total_open": 11587,
      "total_submitted": 60501,
      "total_rejected": 580,
      "total_approved": 40330,
      "total_submitted_pencacah": 20070,
      "total_submitted_respondent": 1,
      "persentase": 78.5,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 2488,
          "total_draft": 64,
          "total_open": 0,
          "total_submitted": 2419,
          "total_rejected": 0,
          "total_approved": 2419,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 97.23,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 1536,
          "total_draft": 35,
          "total_open": 1,
          "total_submitted": 1500,
          "total_rejected": 0,
          "total_approved": 1499,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 97.66,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 4948,
          "total_draft": 28,
          "total_open": 81,
          "total_submitted": 4759,
          "total_rejected": 20,
          "total_approved": 3869,
          "total_submitted_pencacah": 889,
          "total_submitted_respondent": 0,
          "persentase": 96.18,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[021] PARIGI SELATAN",
          "kec_name": "[021] PARIGI SELATAN",
          "total_prelist": 24042,
          "total_draft": 949,
          "total_open": 3482,
          "total_submitted": 19476,
          "total_rejected": 103,
          "total_approved": 12495,
          "total_submitted_pencacah": 6974,
          "total_submitted_respondent": 0,
          "persentase": 81.01,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[022] PARIGI BARAT",
          "kec_name": "[022] PARIGI BARAT",
          "total_prelist": 2389,
          "total_draft": 205,
          "total_open": 423,
          "total_submitted": 1754,
          "total_rejected": 7,
          "total_approved": 1080,
          "total_submitted_pencacah": 667,
          "total_submitted_respondent": 1,
          "persentase": 73.42,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 14577,
          "total_draft": 691,
          "total_open": 2707,
          "total_submitted": 11095,
          "total_rejected": 78,
          "total_approved": 5367,
          "total_submitted_pencacah": 5728,
          "total_submitted_respondent": 0,
          "persentase": 76.11,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 5809,
          "total_draft": 146,
          "total_open": 611,
          "total_submitted": 4763,
          "total_rejected": 110,
          "total_approved": 2674,
          "total_submitted_pencacah": 2081,
          "total_submitted_respondent": 0,
          "persentase": 81.99,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 6884,
          "total_draft": 220,
          "total_open": 1099,
          "total_submitted": 5550,
          "total_rejected": 14,
          "total_approved": 3632,
          "total_submitted_pencacah": 1905,
          "total_submitted_respondent": 0,
          "persentase": 80.62,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 6136,
          "total_draft": 448,
          "total_open": 1458,
          "total_submitted": 4078,
          "total_rejected": 151,
          "total_approved": 3512,
          "total_submitted_pencacah": 565,
          "total_submitted_respondent": 0,
          "persentase": 66.46,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[042] SIDOAN",
          "kec_name": "[042] SIDOAN",
          "total_prelist": 8261,
          "total_draft": 1320,
          "total_open": 1725,
          "total_submitted": 5107,
          "total_rejected": 97,
          "total_approved": 3783,
          "total_submitted_pencacah": 1261,
          "total_submitted_respondent": 0,
          "persentase": 61.82,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[04] POSO",
      "total_prelist": 131047,
      "total_draft": 2919,
      "total_open": 3119,
      "total_submitted": 119772,
      "total_rejected": 5022,
      "total_approved": 94648,
      "total_submitted_pencacah": 21923,
      "total_submitted_respondent": 10,
      "persentase": 91.4,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 11299,
          "total_draft": 305,
          "total_open": 0,
          "total_submitted": 9854,
          "total_rejected": 1127,
          "total_approved": 8426,
          "total_submitted_pencacah": 841,
          "total_submitted_respondent": 1,
          "persentase": 87.21,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 4694,
          "total_draft": 63,
          "total_open": 8,
          "total_submitted": 4502,
          "total_rejected": 116,
          "total_approved": 2456,
          "total_submitted_pencacah": 1880,
          "total_submitted_respondent": 0,
          "persentase": 95.91,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[012] ULUJADI",
          "kec_name": "[012] ULUJADI",
          "total_prelist": 3753,
          "total_draft": 15,
          "total_open": 0,
          "total_submitted": 3737,
          "total_rejected": 1,
          "total_approved": 3356,
          "total_submitted_pencacah": 1,
          "total_submitted_respondent": 0,
          "persentase": 99.57,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 3074,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 3028,
          "total_rejected": 1,
          "total_approved": 2989,
          "total_submitted_pencacah": 8,
          "total_submitted_respondent": 0,
          "persentase": 98.5,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[021] PARIGI SELATAN",
          "kec_name": "[021] PARIGI SELATAN",
          "total_prelist": 1368,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 1364,
          "total_rejected": 0,
          "total_approved": 1316,
          "total_submitted_pencacah": 5,
          "total_submitted_respondent": 0,
          "persentase": 99.71,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 11917,
          "total_draft": 259,
          "total_open": 35,
          "total_submitted": 11241,
          "total_rejected": 349,
          "total_approved": 8227,
          "total_submitted_pencacah": 2755,
          "total_submitted_respondent": 0,
          "persentase": 94.33,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 6349,
          "total_draft": 112,
          "total_open": 180,
          "total_submitted": 5915,
          "total_rejected": 130,
          "total_approved": 4582,
          "total_submitted_pencacah": 1114,
          "total_submitted_respondent": 0,
          "persentase": 93.16,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[032] TORIBULU",
          "kec_name": "[032] TORIBULU",
          "total_prelist": 7357,
          "total_draft": 22,
          "total_open": 167,
          "total_submitted": 7036,
          "total_rejected": 119,
          "total_approved": 6570,
          "total_submitted_pencacah": 194,
          "total_submitted_respondent": 0,
          "persentase": 95.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 7433,
          "total_draft": 15,
          "total_open": 19,
          "total_submitted": 7384,
          "total_rejected": 15,
          "total_approved": 6945,
          "total_submitted_pencacah": 293,
          "total_submitted_respondent": 0,
          "persentase": 99.34,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 2524,
          "total_draft": 95,
          "total_open": 1,
          "total_submitted": 2389,
          "total_rejected": 26,
          "total_approved": 2129,
          "total_submitted_pencacah": 235,
          "total_submitted_respondent": 1,
          "persentase": 94.65,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[042] SIDOAN",
          "kec_name": "[042] SIDOAN",
          "total_prelist": 2868,
          "total_draft": 8,
          "total_open": 6,
          "total_submitted": 2804,
          "total_rejected": 50,
          "total_approved": 2273,
          "total_submitted_pencacah": 513,
          "total_submitted_respondent": 1,
          "persentase": 97.77,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[043] LORE PEORE",
          "kec_name": "[043] LORE PEORE",
          "total_prelist": 2035,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 1870,
          "total_rejected": 154,
          "total_approved": 1814,
          "total_submitted_pencacah": 49,
          "total_submitted_respondent": 0,
          "persentase": 91.89,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 12777,
          "total_draft": 636,
          "total_open": 50,
          "total_submitted": 11266,
          "total_rejected": 813,
          "total_approved": 6851,
          "total_submitted_pencacah": 4306,
          "total_submitted_respondent": 1,
          "persentase": 88.17,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 4986,
          "total_draft": 79,
          "total_open": 50,
          "total_submitted": 4796,
          "total_rejected": 48,
          "total_approved": 4522,
          "total_submitted_pencacah": 37,
          "total_submitted_respondent": 0,
          "persentase": 96.19,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[052] PALASA",
          "kec_name": "[052] PALASA",
          "total_prelist": 8164,
          "total_draft": 183,
          "total_open": 81,
          "total_submitted": 7773,
          "total_rejected": 123,
          "total_approved": 6446,
          "total_submitted_pencacah": 1031,
          "total_submitted_respondent": 0,
          "persentase": 95.21,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 10595,
          "total_draft": 204,
          "total_open": 249,
          "total_submitted": 9132,
          "total_rejected": 998,
          "total_approved": 6556,
          "total_submitted_pencacah": 2337,
          "total_submitted_respondent": 1,
          "persentase": 86.19,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 13222,
          "total_draft": 388,
          "total_open": 1201,
          "total_submitted": 11246,
          "total_rejected": 370,
          "total_approved": 8807,
          "total_submitted_pencacah": 2360,
          "total_submitted_respondent": 3,
          "persentase": 85.06,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[071] POSO KOTA UTARA",
          "kec_name": "[071] POSO KOTA UTARA",
          "total_prelist": 8836,
          "total_draft": 160,
          "total_open": 707,
          "total_submitted": 7672,
          "total_rejected": 295,
          "total_approved": 6275,
          "total_submitted_pencacah": 1325,
          "total_submitted_respondent": 2,
          "persentase": 86.83,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[072] POSO KOTA SELATAN",
          "kec_name": "[072] POSO KOTA SELATAN",
          "total_prelist": 7796,
          "total_draft": 375,
          "total_open": 365,
          "total_submitted": 6763,
          "total_rejected": 287,
          "total_approved": 4108,
          "total_submitted_pencacah": 2639,
          "total_submitted_respondent": 0,
          "persentase": 86.75,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[05] DONGGALA",
      "total_prelist": 144508,
      "total_draft": 2229,
      "total_open": 3631,
      "total_submitted": 136365,
      "total_rejected": 2111,
      "total_approved": 119716,
      "total_submitted_pencacah": 15737,
      "total_submitted_respondent": 5,
      "persentase": 94.37,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 11182,
          "total_draft": 389,
          "total_open": 454,
          "total_submitted": 10247,
          "total_rejected": 61,
          "total_approved": 10043,
          "total_submitted_pencacah": 191,
          "total_submitted_respondent": 0,
          "persentase": 91.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 1982,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 1982,
          "total_rejected": 0,
          "total_approved": 1961,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 100.0,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[080] SOYO JAYA",
          "kec_name": "[080] SOYO JAYA",
          "total_prelist": 19552,
          "total_draft": 288,
          "total_open": 649,
          "total_submitted": 18407,
          "total_rejected": 199,
          "total_approved": 17785,
          "total_submitted_pencacah": 600,
          "total_submitted_respondent": 5,
          "persentase": 94.14,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[081] WALEA BESAR",
          "kec_name": "[081] WALEA BESAR",
          "total_prelist": 12790,
          "total_draft": 17,
          "total_open": 0,
          "total_submitted": 12660,
          "total_rejected": 75,
          "total_approved": 11310,
          "total_submitted_pencacah": 1268,
          "total_submitted_respondent": 0,
          "persentase": 98.98,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[082] TALATAKO",
          "kec_name": "[082] TALATAKO",
          "total_prelist": 5214,
          "total_draft": 238,
          "total_open": 131,
          "total_submitted": 4799,
          "total_rejected": 44,
          "total_approved": 4721,
          "total_submitted_pencacah": 75,
          "total_submitted_respondent": 0,
          "persentase": 92.04,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[090] BUNGKU UTARA",
          "kec_name": "[090] BUNGKU UTARA",
          "total_prelist": 7425,
          "total_draft": 43,
          "total_open": 513,
          "total_submitted": 6761,
          "total_rejected": 104,
          "total_approved": 5777,
          "total_submitted_pencacah": 935,
          "total_submitted_respondent": 0,
          "persentase": 91.06,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[091] TANANTOVEA",
          "kec_name": "[091] TANANTOVEA",
          "total_prelist": 7885,
          "total_draft": 144,
          "total_open": 100,
          "total_submitted": 7620,
          "total_rejected": 20,
          "total_approved": 7333,
          "total_submitted_pencacah": 3,
          "total_submitted_respondent": 0,
          "persentase": 96.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[100] MAMOSALATO",
          "kec_name": "[100] MAMOSALATO",
          "total_prelist": 11172,
          "total_draft": 80,
          "total_open": 122,
          "total_submitted": 10693,
          "total_rejected": 250,
          "total_approved": 8298,
          "total_submitted_pencacah": 2359,
          "total_submitted_respondent": 0,
          "persentase": 95.71,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[101] SINDUE TOMBUSABORA",
          "kec_name": "[101] SINDUE TOMBUSABORA",
          "total_prelist": 6460,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 6452,
          "total_rejected": 6,
          "total_approved": 6401,
          "total_submitted_pencacah": 2,
          "total_submitted_respondent": 0,
          "persentase": 99.88,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[102] SINDUE TOBATA",
          "kec_name": "[102] SINDUE TOBATA",
          "total_prelist": 4752,
          "total_draft": 7,
          "total_open": 0,
          "total_submitted": 4743,
          "total_rejected": 0,
          "total_approved": 4651,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.81,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[120] SIGI BIROMARU",
          "kec_name": "[120] SIGI BIROMARU",
          "total_prelist": 9872,
          "total_draft": 203,
          "total_open": 73,
          "total_submitted": 9374,
          "total_rejected": 217,
          "total_approved": 8173,
          "total_submitted_pencacah": 1197,
          "total_submitted_respondent": 0,
          "persentase": 94.96,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[130] MARAWOLA",
          "kec_name": "[130] MARAWOLA",
          "total_prelist": 10563,
          "total_draft": 89,
          "total_open": 0,
          "total_submitted": 10405,
          "total_rejected": 43,
          "total_approved": 10043,
          "total_submitted_pencacah": 253,
          "total_submitted_respondent": 0,
          "persentase": 98.5,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[131] BALAESANG TANJUNG",
          "kec_name": "[131] BALAESANG TANJUNG",
          "total_prelist": 5281,
          "total_draft": 2,
          "total_open": 0,
          "total_submitted": 5272,
          "total_rejected": 7,
          "total_approved": 5252,
          "total_submitted_pencacah": 5,
          "total_submitted_respondent": 0,
          "persentase": 99.83,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[140] MARAWOLA BARAT",
          "kec_name": "[140] MARAWOLA BARAT",
          "total_prelist": 14070,
          "total_draft": 466,
          "total_open": 1139,
          "total_submitted": 12318,
          "total_rejected": 140,
          "total_approved": 9905,
          "total_submitted_pencacah": 2360,
          "total_submitted_respondent": 0,
          "persentase": 87.55,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[160] SOJOL",
          "kec_name": "[160] SOJOL",
          "total_prelist": 11851,
          "total_draft": 262,
          "total_open": 450,
          "total_submitted": 10198,
          "total_rejected": 925,
          "total_approved": 3740,
          "total_submitted_pencacah": 6456,
          "total_submitted_respondent": 0,
          "persentase": 86.05,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[161] SOJOL UTARA",
          "kec_name": "[161] SOJOL UTARA",
          "total_prelist": 4457,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 4434,
          "total_rejected": 20,
          "total_approved": 4323,
          "total_submitted_pencacah": 33,
          "total_submitted_respondent": 0,
          "persentase": 99.48,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[06] TOLI-TOLI",
      "total_prelist": 109324,
      "total_draft": 2206,
      "total_open": 4209,
      "total_submitted": 101508,
      "total_rejected": 1232,
      "total_approved": 86565,
      "total_submitted_pencacah": 12774,
      "total_submitted_respondent": 1,
      "persentase": 92.85,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 10455,
          "total_draft": 14,
          "total_open": 194,
          "total_submitted": 9916,
          "total_rejected": 283,
          "total_approved": 6964,
          "total_submitted_pencacah": 2855,
          "total_submitted_respondent": 0,
          "persentase": 94.84,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 6506,
          "total_draft": 37,
          "total_open": 211,
          "total_submitted": 6208,
          "total_rejected": 50,
          "total_approved": 5602,
          "total_submitted_pencacah": 471,
          "total_submitted_respondent": 0,
          "persentase": 95.42,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 10887,
          "total_draft": 48,
          "total_open": 45,
          "total_submitted": 10725,
          "total_rejected": 62,
          "total_approved": 10503,
          "total_submitted_pencacah": 62,
          "total_submitted_respondent": 0,
          "persentase": 98.51,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 6221,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 6220,
          "total_rejected": 0,
          "total_approved": 6123,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.98,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[032] TORIBULU",
          "kec_name": "[032] TORIBULU",
          "total_prelist": 4977,
          "total_draft": 95,
          "total_open": 63,
          "total_submitted": 4812,
          "total_rejected": 7,
          "total_approved": 4558,
          "total_submitted_pencacah": 8,
          "total_submitted_respondent": 0,
          "persentase": 96.68,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 33055,
          "total_draft": 1244,
          "total_open": 2416,
          "total_submitted": 28904,
          "total_rejected": 445,
          "total_approved": 21685,
          "total_submitted_pencacah": 6413,
          "total_submitted_respondent": 1,
          "persentase": 87.44,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 5767,
          "total_draft": 92,
          "total_open": 552,
          "total_submitted": 4952,
          "total_rejected": 166,
          "total_approved": 4097,
          "total_submitted_pencacah": 741,
          "total_submitted_respondent": 0,
          "persentase": 85.87,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 17457,
          "total_draft": 356,
          "total_open": 42,
          "total_submitted": 16896,
          "total_rejected": 109,
          "total_approved": 15767,
          "total_submitted_pencacah": 969,
          "total_submitted_respondent": 0,
          "persentase": 96.79,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 9287,
          "total_draft": 21,
          "total_open": 686,
          "total_submitted": 8535,
          "total_rejected": 41,
          "total_approved": 7445,
          "total_submitted_pencacah": 968,
          "total_submitted_respondent": 0,
          "persentase": 91.9,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[061] BATUDAKA",
          "kec_name": "[061] BATUDAKA",
          "total_prelist": 4712,
          "total_draft": 298,
          "total_open": 0,
          "total_submitted": 4340,
          "total_rejected": 69,
          "total_approved": 3821,
          "total_submitted_pencacah": 287,
          "total_submitted_respondent": 0,
          "persentase": 92.11,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[07] BUOL",
      "total_prelist": 74698,
      "total_draft": 2866,
      "total_open": 85,
      "total_submitted": 68804,
      "total_rejected": 2783,
      "total_approved": 59660,
      "total_submitted_pencacah": 8515,
      "total_submitted_respondent": 12,
      "persentase": 92.11,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 5586,
          "total_draft": 63,
          "total_open": 1,
          "total_submitted": 5278,
          "total_rejected": 236,
          "total_approved": 4900,
          "total_submitted_pencacah": 375,
          "total_submitted_respondent": 0,
          "persentase": 94.49,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 16986,
          "total_draft": 493,
          "total_open": 26,
          "total_submitted": 15130,
          "total_rejected": 1288,
          "total_approved": 12078,
          "total_submitted_pencacah": 2911,
          "total_submitted_respondent": 10,
          "persentase": 89.07,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[012] ULUJADI",
          "kec_name": "[012] ULUJADI",
          "total_prelist": 4420,
          "total_draft": 81,
          "total_open": 1,
          "total_submitted": 4147,
          "total_rejected": 190,
          "total_approved": 3663,
          "total_submitted_pencacah": 443,
          "total_submitted_respondent": 0,
          "persentase": 93.82,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 8139,
          "total_draft": 145,
          "total_open": 9,
          "total_submitted": 7523,
          "total_rejected": 452,
          "total_approved": 6803,
          "total_submitted_pencacah": 696,
          "total_submitted_respondent": 0,
          "persentase": 92.43,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[021] PARIGI SELATAN",
          "kec_name": "[021] PARIGI SELATAN",
          "total_prelist": 4367,
          "total_draft": 80,
          "total_open": 16,
          "total_submitted": 4245,
          "total_rejected": 24,
          "total_approved": 3056,
          "total_submitted_pencacah": 1115,
          "total_submitted_respondent": 0,
          "persentase": 97.21,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 8449,
          "total_draft": 482,
          "total_open": 9,
          "total_submitted": 7818,
          "total_rejected": 129,
          "total_approved": 7087,
          "total_submitted_pencacah": 567,
          "total_submitted_respondent": 0,
          "persentase": 92.53,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 6994,
          "total_draft": 203,
          "total_open": 15,
          "total_submitted": 6711,
          "total_rejected": 52,
          "total_approved": 6119,
          "total_submitted_pencacah": 501,
          "total_submitted_respondent": 2,
          "persentase": 95.95,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 4788,
          "total_draft": 195,
          "total_open": 0,
          "total_submitted": 4488,
          "total_rejected": 102,
          "total_approved": 3751,
          "total_submitted_pencacah": 671,
          "total_submitted_respondent": 0,
          "persentase": 93.73,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 5836,
          "total_draft": 146,
          "total_open": 8,
          "total_submitted": 5391,
          "total_rejected": 258,
          "total_approved": 4895,
          "total_submitted_pencacah": 472,
          "total_submitted_respondent": 0,
          "persentase": 92.37,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 6240,
          "total_draft": 713,
          "total_open": 0,
          "total_submitted": 5493,
          "total_rejected": 18,
          "total_approved": 4978,
          "total_submitted_pencacah": 514,
          "total_submitted_respondent": 0,
          "persentase": 88.03,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 2893,
          "total_draft": 265,
          "total_open": 0,
          "total_submitted": 2580,
          "total_rejected": 34,
          "total_approved": 2330,
          "total_submitted_pencacah": 250,
          "total_submitted_respondent": 0,
          "persentase": 89.18,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[08] PARIGI MOUTONG",
      "total_prelist": 212246,
      "total_draft": 1795,
      "total_open": 1246,
      "total_submitted": 204479,
      "total_rejected": 4395,
      "total_approved": 162701,
      "total_submitted_pencacah": 41437,
      "total_submitted_respondent": 5,
      "persentase": 96.34,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 9948,
          "total_draft": 29,
          "total_open": 0,
          "total_submitted": 9832,
          "total_rejected": 83,
          "total_approved": 6376,
          "total_submitted_pencacah": 3456,
          "total_submitted_respondent": 0,
          "persentase": 98.83,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 10798,
          "total_draft": 45,
          "total_open": 0,
          "total_submitted": 10594,
          "total_rejected": 140,
          "total_approved": 7783,
          "total_submitted_pencacah": 2811,
          "total_submitted_respondent": 0,
          "persentase": 98.11,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[012] ULUJADI",
          "kec_name": "[012] ULUJADI",
          "total_prelist": 7801,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 7594,
          "total_rejected": 201,
          "total_approved": 4183,
          "total_submitted_pencacah": 3409,
          "total_submitted_respondent": 0,
          "persentase": 97.35,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 15908,
          "total_draft": 453,
          "total_open": 960,
          "total_submitted": 13384,
          "total_rejected": 1052,
          "total_approved": 6614,
          "total_submitted_pencacah": 6762,
          "total_submitted_respondent": 4,
          "persentase": 84.13,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[021] PARIGI SELATAN",
          "kec_name": "[021] PARIGI SELATAN",
          "total_prelist": 10918,
          "total_draft": 20,
          "total_open": 0,
          "total_submitted": 10382,
          "total_rejected": 505,
          "total_approved": 7497,
          "total_submitted_pencacah": 2884,
          "total_submitted_respondent": 1,
          "persentase": 95.09,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[022] PARIGI BARAT",
          "kec_name": "[022] PARIGI BARAT",
          "total_prelist": 3402,
          "total_draft": 6,
          "total_open": 0,
          "total_submitted": 3380,
          "total_rejected": 16,
          "total_approved": 2297,
          "total_submitted_pencacah": 1079,
          "total_submitted_respondent": 0,
          "persentase": 99.35,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[023] PARIGI UTARA",
          "kec_name": "[023] PARIGI UTARA",
          "total_prelist": 2676,
          "total_draft": 7,
          "total_open": 0,
          "total_submitted": 2668,
          "total_rejected": 0,
          "total_approved": 2667,
          "total_submitted_pencacah": 1,
          "total_submitted_respondent": 0,
          "persentase": 99.7,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[024] PARIGI TENGAH",
          "kec_name": "[024] PARIGI TENGAH",
          "total_prelist": 4165,
          "total_draft": 45,
          "total_open": 0,
          "total_submitted": 4054,
          "total_rejected": 62,
          "total_approved": 3559,
          "total_submitted_pencacah": 494,
          "total_submitted_respondent": 0,
          "persentase": 97.33,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 10842,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 10835,
          "total_rejected": 3,
          "total_approved": 10826,
          "total_submitted_pencacah": 2,
          "total_submitted_respondent": 0,
          "persentase": 99.94,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 10973,
          "total_draft": 6,
          "total_open": 0,
          "total_submitted": 10747,
          "total_rejected": 178,
          "total_approved": 8497,
          "total_submitted_pencacah": 2249,
          "total_submitted_respondent": 0,
          "persentase": 97.94,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[032] TORIBULU",
          "kec_name": "[032] TORIBULU",
          "total_prelist": 7773,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 7762,
          "total_rejected": 1,
          "total_approved": 7759,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.86,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[033] SINIU",
          "kec_name": "[033] SINIU",
          "total_prelist": 4994,
          "total_draft": 18,
          "total_open": 0,
          "total_submitted": 4476,
          "total_rejected": 499,
          "total_approved": 3578,
          "total_submitted_pencacah": 895,
          "total_submitted_respondent": 0,
          "persentase": 89.63,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 9661,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 9660,
          "total_rejected": 0,
          "total_approved": 9523,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.99,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 14182,
          "total_draft": 80,
          "total_open": 2,
          "total_submitted": 13954,
          "total_rejected": 143,
          "total_approved": 10854,
          "total_submitted_pencacah": 2950,
          "total_submitted_respondent": 0,
          "persentase": 98.39,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[042] SIDOAN",
          "kec_name": "[042] SIDOAN",
          "total_prelist": 6611,
          "total_draft": 109,
          "total_open": 1,
          "total_submitted": 6479,
          "total_rejected": 10,
          "total_approved": 5476,
          "total_submitted_pencacah": 1002,
          "total_submitted_respondent": 0,
          "persentase": 98.0,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 8213,
          "total_draft": 4,
          "total_open": 0,
          "total_submitted": 8209,
          "total_rejected": 0,
          "total_approved": 8203,
          "total_submitted_pencacah": 4,
          "total_submitted_respondent": 0,
          "persentase": 99.95,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 15708,
          "total_draft": 250,
          "total_open": 117,
          "total_submitted": 14781,
          "total_rejected": 547,
          "total_approved": 11383,
          "total_submitted_pencacah": 3396,
          "total_submitted_respondent": 0,
          "persentase": 94.1,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[052] PALASA",
          "kec_name": "[052] PALASA",
          "total_prelist": 11747,
          "total_draft": 4,
          "total_open": 0,
          "total_submitted": 11664,
          "total_rejected": 67,
          "total_approved": 11593,
          "total_submitted_pencacah": 64,
          "total_submitted_respondent": 0,
          "persentase": 99.29,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 10317,
          "total_draft": 96,
          "total_open": 2,
          "total_submitted": 9904,
          "total_rejected": 223,
          "total_approved": 6606,
          "total_submitted_pencacah": 3297,
          "total_submitted_respondent": 0,
          "persentase": 96.0,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[061] BATUDAKA",
          "kec_name": "[061] BATUDAKA",
          "total_prelist": 10733,
          "total_draft": 14,
          "total_open": 0,
          "total_submitted": 10651,
          "total_rejected": 57,
          "total_approved": 8990,
          "total_submitted_pencacah": 1656,
          "total_submitted_respondent": 0,
          "persentase": 99.24,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[062] TAOPA",
          "kec_name": "[062] TAOPA",
          "total_prelist": 7164,
          "total_draft": 591,
          "total_open": 164,
          "total_submitted": 5901,
          "total_rejected": 500,
          "total_approved": 3911,
          "total_submitted_pencacah": 1990,
          "total_submitted_respondent": 0,
          "persentase": 82.37,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[063] BOLANO",
          "kec_name": "[063] BOLANO",
          "total_prelist": 8142,
          "total_draft": 16,
          "total_open": 0,
          "total_submitted": 8014,
          "total_rejected": 103,
          "total_approved": 4974,
          "total_submitted_pencacah": 3034,
          "total_submitted_respondent": 0,
          "persentase": 98.43,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[064] ONGKA MALINO",
          "kec_name": "[064] ONGKA MALINO",
          "total_prelist": 9570,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 9554,
          "total_rejected": 5,
          "total_approved": 9552,
          "total_submitted_pencacah": 2,
          "total_submitted_respondent": 0,
          "persentase": 99.83,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[09] TOJO UNA-UNA",
      "total_prelist": 75431,
      "total_draft": 2205,
      "total_open": 1774,
      "total_submitted": 65650,
      "total_rejected": 5574,
      "total_approved": 52418,
      "total_submitted_pencacah": 13043,
      "total_submitted_respondent": 5,
      "persentase": 87.03,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 6340,
          "total_draft": 570,
          "total_open": 154,
          "total_submitted": 5055,
          "total_rejected": 552,
          "total_approved": 3259,
          "total_submitted_pencacah": 1787,
          "total_submitted_respondent": 0,
          "persentase": 79.73,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 6381,
          "total_draft": 44,
          "total_open": 63,
          "total_submitted": 6174,
          "total_rejected": 68,
          "total_approved": 5292,
          "total_submitted_pencacah": 863,
          "total_submitted_respondent": 0,
          "persentase": 96.76,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 8877,
          "total_draft": 17,
          "total_open": 0,
          "total_submitted": 8596,
          "total_rejected": 214,
          "total_approved": 7769,
          "total_submitted_pencacah": 778,
          "total_submitted_respondent": 1,
          "persentase": 96.83,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 13169,
          "total_draft": 42,
          "total_open": 458,
          "total_submitted": 12069,
          "total_rejected": 506,
          "total_approved": 11425,
          "total_submitted_pencacah": 580,
          "total_submitted_respondent": 1,
          "persentase": 91.65,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 10919,
          "total_draft": 331,
          "total_open": 188,
          "total_submitted": 9219,
          "total_rejected": 1175,
          "total_approved": 6688,
          "total_submitted_pencacah": 2526,
          "total_submitted_respondent": 0,
          "persentase": 84.43,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[051] RATOLINDO",
          "kec_name": "[051] RATOLINDO",
          "total_prelist": 13981,
          "total_draft": 106,
          "total_open": 572,
          "total_submitted": 11815,
          "total_rejected": 1477,
          "total_approved": 9772,
          "total_submitted_pencacah": 2028,
          "total_submitted_respondent": 3,
          "persentase": 84.51,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 3477,
          "total_draft": 560,
          "total_open": 237,
          "total_submitted": 2190,
          "total_rejected": 473,
          "total_approved": 1210,
          "total_submitted_pencacah": 980,
          "total_submitted_respondent": 0,
          "persentase": 62.99,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[061] BATUDAKA",
          "kec_name": "[061] BATUDAKA",
          "total_prelist": 2249,
          "total_draft": 0,
          "total_open": 9,
          "total_submitted": 2071,
          "total_rejected": 169,
          "total_approved": 1250,
          "total_submitted_pencacah": 821,
          "total_submitted_respondent": 0,
          "persentase": 92.09,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 4083,
          "total_draft": 142,
          "total_open": 93,
          "total_submitted": 3374,
          "total_rejected": 474,
          "total_approved": 2609,
          "total_submitted_pencacah": 752,
          "total_submitted_respondent": 0,
          "persentase": 82.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[080] SOYO JAYA",
          "kec_name": "[080] SOYO JAYA",
          "total_prelist": 2066,
          "total_draft": 212,
          "total_open": 0,
          "total_submitted": 1751,
          "total_rejected": 100,
          "total_approved": 1378,
          "total_submitted_pencacah": 369,
          "total_submitted_respondent": 0,
          "persentase": 84.75,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[081] WALEA BESAR",
          "kec_name": "[081] WALEA BESAR",
          "total_prelist": 1700,
          "total_draft": 9,
          "total_open": 0,
          "total_submitted": 1623,
          "total_rejected": 66,
          "total_approved": 758,
          "total_submitted_pencacah": 858,
          "total_submitted_respondent": 0,
          "persentase": 95.47,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[082] TALATAKO",
          "kec_name": "[082] TALATAKO",
          "total_prelist": 2189,
          "total_draft": 172,
          "total_open": 0,
          "total_submitted": 1713,
          "total_rejected": 300,
          "total_approved": 1008,
          "total_submitted_pencacah": 701,
          "total_submitted_respondent": 0,
          "persentase": 78.25,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[10] SIGI",
      "total_prelist": 131757,
      "total_draft": 1635,
      "total_open": 1550,
      "total_submitted": 125936,
      "total_rejected": 2493,
      "total_approved": 114289,
      "total_submitted_pencacah": 9849,
      "total_submitted_respondent": 6,
      "persentase": 95.58,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 3772,
          "total_draft": 0,
          "total_open": 0,
          "total_submitted": 3768,
          "total_rejected": 4,
          "total_approved": 3768,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.89,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 4072,
          "total_draft": 9,
          "total_open": 0,
          "total_submitted": 4053,
          "total_rejected": 10,
          "total_approved": 3363,
          "total_submitted_pencacah": 690,
          "total_submitted_respondent": 0,
          "persentase": 99.53,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 7120,
          "total_draft": 68,
          "total_open": 0,
          "total_submitted": 7002,
          "total_rejected": 26,
          "total_approved": 6031,
          "total_submitted_pencacah": 667,
          "total_submitted_respondent": 0,
          "persentase": 98.34,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 2317,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 2309,
          "total_rejected": 2,
          "total_approved": 2247,
          "total_submitted_pencacah": 47,
          "total_submitted_respondent": 0,
          "persentase": 99.65,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 2837,
          "total_draft": 2,
          "total_open": 0,
          "total_submitted": 2805,
          "total_rejected": 26,
          "total_approved": 2697,
          "total_submitted_pencacah": 2,
          "total_submitted_respondent": 0,
          "persentase": 98.87,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 13580,
          "total_draft": 382,
          "total_open": 62,
          "total_submitted": 12116,
          "total_rejected": 1001,
          "total_approved": 9845,
          "total_submitted_pencacah": 2178,
          "total_submitted_respondent": 1,
          "persentase": 89.22,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 6825,
          "total_draft": 25,
          "total_open": 0,
          "total_submitted": 6640,
          "total_rejected": 155,
          "total_approved": 5474,
          "total_submitted_pencacah": 1145,
          "total_submitted_respondent": 0,
          "persentase": 97.29,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[080] SOYO JAYA",
          "kec_name": "[080] SOYO JAYA",
          "total_prelist": 8991,
          "total_draft": 55,
          "total_open": 164,
          "total_submitted": 8738,
          "total_rejected": 34,
          "total_approved": 8607,
          "total_submitted_pencacah": 33,
          "total_submitted_respondent": 0,
          "persentase": 97.19,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[090] BUNGKU UTARA",
          "kec_name": "[090] BUNGKU UTARA",
          "total_prelist": 8914,
          "total_draft": 64,
          "total_open": 0,
          "total_submitted": 8797,
          "total_rejected": 53,
          "total_approved": 8537,
          "total_submitted_pencacah": 10,
          "total_submitted_respondent": 0,
          "persentase": 98.69,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[100] MAMOSALATO",
          "kec_name": "[100] MAMOSALATO",
          "total_prelist": 5284,
          "total_draft": 36,
          "total_open": 22,
          "total_submitted": 5106,
          "total_rejected": 117,
          "total_approved": 4993,
          "total_submitted_pencacah": 4,
          "total_submitted_respondent": 0,
          "persentase": 96.63,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[110] DOLO",
          "kec_name": "[110] DOLO",
          "total_prelist": 11254,
          "total_draft": 206,
          "total_open": 4,
          "total_submitted": 10472,
          "total_rejected": 569,
          "total_approved": 7870,
          "total_submitted_pencacah": 2548,
          "total_submitted_respondent": 1,
          "persentase": 93.05,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[120] SIGI BIROMARU",
          "kec_name": "[120] SIGI BIROMARU",
          "total_prelist": 24333,
          "total_draft": 382,
          "total_open": 878,
          "total_submitted": 22864,
          "total_rejected": 177,
          "total_approved": 21665,
          "total_submitted_pencacah": 1001,
          "total_submitted_respondent": 2,
          "persentase": 93.96,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[121] SIGI KOTA",
          "kec_name": "[121] SIGI KOTA",
          "total_prelist": 8990,
          "total_draft": 178,
          "total_open": 269,
          "total_submitted": 8531,
          "total_rejected": 12,
          "total_approved": 8123,
          "total_submitted_pencacah": 196,
          "total_submitted_respondent": 0,
          "persentase": 94.89,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[130] MARAWOLA",
          "kec_name": "[130] MARAWOLA",
          "total_prelist": 15750,
          "total_draft": 211,
          "total_open": 150,
          "total_submitted": 15158,
          "total_rejected": 185,
          "total_approved": 13861,
          "total_submitted_pencacah": 1093,
          "total_submitted_respondent": 2,
          "persentase": 96.24,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[140] MARAWOLA BARAT",
          "kec_name": "[140] MARAWOLA BARAT",
          "total_prelist": 2751,
          "total_draft": 1,
          "total_open": 1,
          "total_submitted": 2749,
          "total_rejected": 0,
          "total_approved": 2686,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 99.93,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[150] KINOVARO",
          "kec_name": "[150] KINOVARO",
          "total_prelist": 4967,
          "total_draft": 15,
          "total_open": 0,
          "total_submitted": 4828,
          "total_rejected": 122,
          "total_approved": 4522,
          "total_submitted_pencacah": 235,
          "total_submitted_respondent": 0,
          "persentase": 97.2,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[11] BANGGAI LAUT",
      "total_prelist": 34407,
      "total_draft": 1635,
      "total_open": 193,
      "total_submitted": 32278,
      "total_rejected": 277,
      "total_approved": 30786,
      "total_submitted_pencacah": 1236,
      "total_submitted_respondent": 20,
      "persentase": 93.81,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 3995,
          "total_draft": 150,
          "total_open": 13,
          "total_submitted": 3742,
          "total_rejected": 88,
          "total_approved": 3634,
          "total_submitted_pencacah": 101,
          "total_submitted_respondent": 0,
          "persentase": 93.67,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 2544,
          "total_draft": 191,
          "total_open": 0,
          "total_submitted": 2343,
          "total_rejected": 9,
          "total_approved": 2317,
          "total_submitted_pencacah": 7,
          "total_submitted_respondent": 0,
          "persentase": 92.1,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 3287,
          "total_draft": 192,
          "total_open": 0,
          "total_submitted": 3078,
          "total_rejected": 10,
          "total_approved": 2440,
          "total_submitted_pencacah": 638,
          "total_submitted_respondent": 0,
          "persentase": 93.64,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 12615,
          "total_draft": 663,
          "total_open": 6,
          "total_submitted": 11872,
          "total_rejected": 67,
          "total_approved": 11350,
          "total_submitted_pencacah": 376,
          "total_submitted_respondent": 20,
          "persentase": 94.11,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 4073,
          "total_draft": 1,
          "total_open": 0,
          "total_submitted": 4063,
          "total_rejected": 8,
          "total_approved": 4034,
          "total_submitted_pencacah": 14,
          "total_submitted_respondent": 0,
          "persentase": 99.75,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 2647,
          "total_draft": 185,
          "total_open": 0,
          "total_submitted": 2443,
          "total_rejected": 18,
          "total_approved": 2384,
          "total_submitted_pencacah": 54,
          "total_submitted_respondent": 0,
          "persentase": 92.29,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 5246,
          "total_draft": 253,
          "total_open": 174,
          "total_submitted": 4737,
          "total_rejected": 77,
          "total_approved": 4627,
          "total_submitted_pencacah": 46,
          "total_submitted_respondent": 0,
          "persentase": 90.3,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[12] MOROWALI UTARA",
      "total_prelist": 53482,
      "total_draft": 1084,
      "total_open": 2997,
      "total_submitted": 47977,
      "total_rejected": 1244,
      "total_approved": 39923,
      "total_submitted_pencacah": 7896,
      "total_submitted_respondent": 1,
      "persentase": 89.71,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[000] -",
          "kec_name": "[000] -",
          "total_prelist": 1,
          "total_draft": 0,
          "total_open": 1,
          "total_submitted": 0,
          "total_rejected": 0,
          "total_approved": 0,
          "total_submitted_pencacah": 0,
          "total_submitted_respondent": 0,
          "persentase": 0.0,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 4979,
          "total_draft": 17,
          "total_open": 158,
          "total_submitted": 4713,
          "total_rejected": 80,
          "total_approved": 3268,
          "total_submitted_pencacah": 1373,
          "total_submitted_respondent": 0,
          "persentase": 94.66,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 6459,
          "total_draft": 124,
          "total_open": 608,
          "total_submitted": 5683,
          "total_rejected": 36,
          "total_approved": 4959,
          "total_submitted_pencacah": 708,
          "total_submitted_respondent": 0,
          "persentase": 87.99,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 3685,
          "total_draft": 28,
          "total_open": 42,
          "total_submitted": 3597,
          "total_rejected": 8,
          "total_approved": 3544,
          "total_submitted_pencacah": 10,
          "total_submitted_respondent": 0,
          "persentase": 97.61,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 8757,
          "total_draft": 309,
          "total_open": 957,
          "total_submitted": 7373,
          "total_rejected": 108,
          "total_approved": 5221,
          "total_submitted_pencacah": 2140,
          "total_submitted_respondent": 1,
          "persentase": 84.2,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[050] PETASIA",
          "kec_name": "[050] PETASIA",
          "total_prelist": 8976,
          "total_draft": 367,
          "total_open": 383,
          "total_submitted": 8096,
          "total_rejected": 50,
          "total_approved": 6626,
          "total_submitted_pencacah": 1469,
          "total_submitted_respondent": 0,
          "persentase": 90.2,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[060] PETASIA BARAT",
          "kec_name": "[060] PETASIA BARAT",
          "total_prelist": 3171,
          "total_draft": 44,
          "total_open": 189,
          "total_submitted": 2913,
          "total_rejected": 5,
          "total_approved": 2846,
          "total_submitted_pencacah": 64,
          "total_submitted_respondent": 0,
          "persentase": 91.86,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[070] MORI UTARA",
          "kec_name": "[070] MORI UTARA",
          "total_prelist": 4427,
          "total_draft": 164,
          "total_open": 9,
          "total_submitted": 4231,
          "total_rejected": 19,
          "total_approved": 3162,
          "total_submitted_pencacah": 1069,
          "total_submitted_respondent": 0,
          "persentase": 95.57,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[080] SOYO JAYA",
          "kec_name": "[080] SOYO JAYA",
          "total_prelist": 3844,
          "total_draft": 18,
          "total_open": 123,
          "total_submitted": 3647,
          "total_rejected": 48,
          "total_approved": 3596,
          "total_submitted_pencacah": 42,
          "total_submitted_respondent": 0,
          "persentase": 94.88,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[090] BUNGKU UTARA",
          "kec_name": "[090] BUNGKU UTARA",
          "total_prelist": 5349,
          "total_draft": 1,
          "total_open": 358,
          "total_submitted": 4673,
          "total_rejected": 307,
          "total_approved": 4533,
          "total_submitted_pencacah": 138,
          "total_submitted_respondent": 0,
          "persentase": 87.36,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[100] MAMOSALATO",
          "kec_name": "[100] MAMOSALATO",
          "total_prelist": 3834,
          "total_draft": 12,
          "total_open": 169,
          "total_submitted": 3051,
          "total_rejected": 583,
          "total_approved": 2168,
          "total_submitted_pencacah": 883,
          "total_submitted_respondent": 0,
          "persentase": 79.58,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    },
    {
      "kabupaten": "[71] PALU",
      "total_prelist": 225891,
      "total_draft": 14832,
      "total_open": 45116,
      "total_submitted": 162433,
      "total_rejected": 3156,
      "total_approved": 112551,
      "total_submitted_pencacah": 48225,
      "total_submitted_respondent": 43,
      "persentase": 71.91,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "kecamatan_list": [
        {
          "kecamatan": "[010] PALU BARAT",
          "kec_name": "[010] PALU BARAT",
          "total_prelist": 26262,
          "total_draft": 1212,
          "total_open": 3383,
          "total_submitted": 21363,
          "total_rejected": 266,
          "total_approved": 9687,
          "total_submitted_pencacah": 11577,
          "total_submitted_respondent": 5,
          "persentase": 81.35,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[011] TATANGA",
          "kec_name": "[011] TATANGA",
          "total_prelist": 30785,
          "total_draft": 1440,
          "total_open": 3912,
          "total_submitted": 24953,
          "total_rejected": 459,
          "total_approved": 15287,
          "total_submitted_pencacah": 9433,
          "total_submitted_respondent": 6,
          "persentase": 81.06,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[012] ULUJADI",
          "kec_name": "[012] ULUJADI",
          "total_prelist": 19465,
          "total_draft": 910,
          "total_open": 3296,
          "total_submitted": 15091,
          "total_rejected": 134,
          "total_approved": 12671,
          "total_submitted_pencacah": 2262,
          "total_submitted_respondent": 3,
          "persentase": 77.53,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[020] PALU SELATAN",
          "kec_name": "[020] PALU SELATAN",
          "total_prelist": 42976,
          "total_draft": 3970,
          "total_open": 11756,
          "total_submitted": 26291,
          "total_rejected": 896,
          "total_approved": 21838,
          "total_submitted_pencacah": 4069,
          "total_submitted_respondent": 3,
          "persentase": 61.18,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[030] PALU TIMUR",
          "kec_name": "[030] PALU TIMUR",
          "total_prelist": 25976,
          "total_draft": 1647,
          "total_open": 4636,
          "total_submitted": 18959,
          "total_rejected": 639,
          "total_approved": 13244,
          "total_submitted_pencacah": 5565,
          "total_submitted_respondent": 11,
          "persentase": 72.99,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[031] MANTIKULORE",
          "kec_name": "[031] MANTIKULORE",
          "total_prelist": 55125,
          "total_draft": 3963,
          "total_open": 14420,
          "total_submitted": 36073,
          "total_rejected": 596,
          "total_approved": 25559,
          "total_submitted_pencacah": 10128,
          "total_submitted_respondent": 9,
          "persentase": 65.44,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[040] PALU UTARA",
          "kec_name": "[040] PALU UTARA",
          "total_prelist": 13578,
          "total_draft": 1066,
          "total_open": 2084,
          "total_submitted": 10352,
          "total_rejected": 56,
          "total_approved": 8127,
          "total_submitted_pencacah": 2090,
          "total_submitted_respondent": 4,
          "persentase": 76.24,
          "new_usaha": 0,
          "new_rumah": 0
        },
        {
          "kecamatan": "[041] TAWAELI",
          "kec_name": "[041] TAWAELI",
          "total_prelist": 11724,
          "total_draft": 624,
          "total_open": 1629,
          "total_submitted": 9351,
          "total_rejected": 110,
          "total_approved": 6138,
          "total_submitted_pencacah": 3101,
          "total_submitted_respondent": 2,
          "persentase": 79.76,
          "new_usaha": 0,
          "new_rumah": 0
        }
      ]
    }
  ]
};
