window.IPAS_DATA = {
  "updated_at": "2026-06-14T17:40:03.138447+08:00",
  "se_umum": [
    {
      "kabupaten": "[01] BANGGAI KEPULAUAN",
      "total_prelist": 43840,
      "total_draft": 164,
      "total_open": 43587,
      "total_submitted": 89,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.2,
      "today_completed": 45,
      "yesterday_completed": 3,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 1,
      "new_businesses": [
        {
          "name": "TK Negeri Lolantang",
          "code": "7201 - SE26mqbsbwAD94",
          "date": "yesterday",
          "status": "DRAFT"
        }
      ]
    },
    {
      "kabupaten": "[02] BANGGAI",
      "total_prelist": 138112,
      "total_draft": 7,
      "total_open": 138101,
      "total_submitted": 4,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 1,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 1,
      "new_businesses": [
        {
          "name": "AWIEN FRISKILA TAUNG / ",
          "code": "7202031006000100 - AWIEN FRISKILA TAUNG /  - 1 /  - 1 - 1. Ya",
          "date": "yesterday",
          "status": "DRAFT"
        }
      ]
    },
    {
      "kabupaten": "[03] MOROWALI",
      "total_prelist": 47729,
      "total_draft": 1,
      "total_open": 47728,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[04] POSO",
      "total_prelist": 105398,
      "total_draft": 75,
      "total_open": 105284,
      "total_submitted": 39,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.04,
      "today_completed": 2,
      "yesterday_completed": 2,
      "two_days_ago_completed": 3,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 2,
      "new_businesses": [
        {
          "name": "Puskesmas Tonusu",
          "code": "7204 - SE26mqbnxk7435",
          "date": "yesterday",
          "status": "SUBMITTED RESPONDENT"
        },
        {
          "name": "Jasa Layanan Puskesmas",
          "code": "7204 - SE26mqbpkk7B00",
          "date": "yesterday",
          "status": "DRAFT"
        }
      ]
    },
    {
      "kabupaten": "[05] DONGGALA",
      "total_prelist": 105502,
      "total_draft": 18,
      "total_open": 105477,
      "total_submitted": 6,
      "total_rejected": 1,
      "total_approved": 0,
      "persentase": 0.01,
      "today_completed": 1,
      "yesterday_completed": 1,
      "two_days_ago_completed": 3,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[06] TOLI-TOLI",
      "total_prelist": 75959,
      "total_draft": 16,
      "total_open": 75943,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[07] BUOL",
      "total_prelist": 57328,
      "total_draft": 130,
      "total_open": 57152,
      "total_submitted": 46,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.08,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[08] PARIGI MOUTONG",
      "total_prelist": 169384,
      "total_draft": 8,
      "total_open": 169370,
      "total_submitted": 4,
      "total_rejected": 2,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[09] TOJO UNA-UNA",
      "total_prelist": 57913,
      "total_draft": 4,
      "total_open": 57904,
      "total_submitted": 5,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.01,
      "today_completed": 1,
      "yesterday_completed": 1,
      "two_days_ago_completed": 1,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[10] SIGI",
      "total_prelist": 105000,
      "total_draft": 0,
      "total_open": 104982,
      "total_submitted": 18,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.02,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[11] BANGGAI LAUT",
      "total_prelist": 27552,
      "total_draft": 4,
      "total_open": 27523,
      "total_submitted": 25,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.09,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[12] MOROWALI UTARA",
      "total_prelist": 42449,
      "total_draft": 5,
      "total_open": 42425,
      "total_submitted": 19,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.04,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 1,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[71] PALU",
      "total_prelist": 164079,
      "total_draft": 33,
      "total_open": 164027,
      "total_submitted": 19,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.01,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    }
  ],
  "se_ub": [
    {
      "kabupaten": "[01] BANGGAI KEPULAUAN",
      "total_prelist": 6,
      "total_draft": 1,
      "total_open": 1,
      "total_submitted": 4,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 66.67,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[02] BANGGAI",
      "total_prelist": 172,
      "total_draft": 4,
      "total_open": 167,
      "total_submitted": 1,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.58,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[03] MOROWALI",
      "total_prelist": 161,
      "total_draft": 2,
      "total_open": 158,
      "total_submitted": 1,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.62,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[04] POSO",
      "total_prelist": 92,
      "total_draft": 4,
      "total_open": 86,
      "total_submitted": 2,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 2.17,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[05] DONGGALA",
      "total_prelist": 57,
      "total_draft": 0,
      "total_open": 57,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[06] TOLI-TOLI",
      "total_prelist": 58,
      "total_draft": 0,
      "total_open": 44,
      "total_submitted": 14,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 24.14,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[07] BUOL",
      "total_prelist": 17,
      "total_draft": 5,
      "total_open": 10,
      "total_submitted": 2,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 11.76,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[08] PARIGI MOUTONG",
      "total_prelist": 65,
      "total_draft": 0,
      "total_open": 65,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[09] TOJO UNA-UNA",
      "total_prelist": 15,
      "total_draft": 2,
      "total_open": 11,
      "total_submitted": 2,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 13.33,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[10] SIGI",
      "total_prelist": 22,
      "total_draft": 0,
      "total_open": 22,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[11] BANGGAI LAUT",
      "total_prelist": 7,
      "total_draft": 3,
      "total_open": 2,
      "total_submitted": 2,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 28.57,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[12] MOROWALI UTARA",
      "total_prelist": 173,
      "total_draft": 0,
      "total_open": 172,
      "total_submitted": 1,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.58,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[71] PALU",
      "total_prelist": 419,
      "total_draft": 6,
      "total_open": 405,
      "total_submitted": 8,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 1.91,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_businesses": []
    }
  ],
  "se_umum_prov_total": 1140245,
  "se_ub_prov_total": 1264
};
