window.IPAS_DATA = {
  "updated_at": "2026-06-17T09:49:02.280052+08:00",
  "se_umum": [
    {
      "kabupaten": "[01] BANGGAI KEPULAUAN",
      "total_prelist": 44099,
      "total_draft": 649,
      "total_open": 42925,
      "total_submitted": 634,
      "total_rejected": 39,
      "total_approved": 55,
      "persentase": 1.44,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 95,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[02] BANGGAI",
      "total_prelist": 139076,
      "total_draft": 696,
      "total_open": 136228,
      "total_submitted": 2209,
      "total_rejected": 56,
      "total_approved": 220,
      "persentase": 1.59,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 192,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[03] MOROWALI",
      "total_prelist": 48186,
      "total_draft": 232,
      "total_open": 47471,
      "total_submitted": 565,
      "total_rejected": 25,
      "total_approved": 57,
      "persentase": 1.17,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 184,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[04] POSO",
      "total_prelist": 105984,
      "total_draft": 520,
      "total_open": 103197,
      "total_submitted": 2291,
      "total_rejected": 115,
      "total_approved": 240,
      "persentase": 2.16,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 129,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[05] DONGGALA",
      "total_prelist": 106145,
      "total_draft": 540,
      "total_open": 104226,
      "total_submitted": 1444,
      "total_rejected": 126,
      "total_approved": 313,
      "persentase": 1.36,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 144,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[06] TOLI-TOLI",
      "total_prelist": 76628,
      "total_draft": 613,
      "total_open": 75129,
      "total_submitted": 1001,
      "total_rejected": 80,
      "total_approved": 42,
      "persentase": 1.31,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 251,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[07] BUOL",
      "total_prelist": 57750,
      "total_draft": 596,
      "total_open": 56330,
      "total_submitted": 909,
      "total_rejected": 93,
      "total_approved": 19,
      "persentase": 1.57,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 161,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[08] PARIGI MOUTONG",
      "total_prelist": 170051,
      "total_draft": 450,
      "total_open": 167612,
      "total_submitted": 2031,
      "total_rejected": 210,
      "total_approved": 238,
      "persentase": 1.19,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 71,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[09] TOJO UNA-UNA",
      "total_prelist": 58561,
      "total_draft": 297,
      "total_open": 56664,
      "total_submitted": 1633,
      "total_rejected": 158,
      "total_approved": 300,
      "persentase": 2.79,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 229,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[10] SIGI",
      "total_prelist": 105487,
      "total_draft": 335,
      "total_open": 103678,
      "total_submitted": 1518,
      "total_rejected": 84,
      "total_approved": 216,
      "persentase": 1.44,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 160,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[11] BANGGAI LAUT",
      "total_prelist": 27789,
      "total_draft": 46,
      "total_open": 27182,
      "total_submitted": 583,
      "total_rejected": 49,
      "total_approved": 149,
      "persentase": 2.1,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 121,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[12] MOROWALI UTARA",
      "total_prelist": 42561,
      "total_draft": 111,
      "total_open": 42017,
      "total_submitted": 432,
      "total_rejected": 21,
      "total_approved": 26,
      "persentase": 1.02,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[71] PALU",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    }
  ],
  "se_ub": [
    {
      "kabupaten": "[01] BANGGAI KEPULAUAN",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[02] BANGGAI",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[03] MOROWALI",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[04] POSO",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[05] DONGGALA",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[06] TOLI-TOLI",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[07] BUOL",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[08] PARIGI MOUTONG",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[09] TOJO UNA-UNA",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[10] SIGI",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[11] BANGGAI LAUT",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[12] MOROWALI UTARA",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    },
    {
      "kabupaten": "[71] PALU",
      "total_prelist": 0,
      "total_draft": 0,
      "total_open": 0,
      "total_submitted": 0,
      "total_rejected": 0,
      "total_approved": 0,
      "persentase": 0.0,
      "today_completed": 0,
      "yesterday_completed": 0,
      "two_days_ago_completed": 0,
      "new_usaha_today": 0,
      "new_usaha_yesterday": 0,
      "new_rumah_today": 0,
      "new_rumah_yesterday": 0,
      "new_usaha_overall": 0,
      "new_rumah_overall": 0,
      "new_businesses": []
    }
  ],
  "se_umum_prov_total": 982317,
  "se_ub_prov_total": 0,
  "se_umum_prov_new_total": 1737,
  "se_ub_prov_new_total": 0,
  "se_umum_prov_new_rumah_total": 0,
  "se_ub_prov_new_rumah_total": 0
};
