import json
import datetime

# We can reuse the cache generated by scrape_via_api.py
with open('all_companies_cache.json', 'r') as f:
    data = json.load(f)

today = datetime.datetime.now(datetime.timezone.utc).date()
print(f"Total data: {len(data)}")

counts = {}
for d in data:
    kab = d['region']['level2']['name']
    if kab not in counts:
        counts[kab] = {'total': 0, 'completed': 0, 'today': 0, 'yesterday': 0}
    
    counts[kab]['total'] += 1
    
    status = d.get('assignmentStatusAlias', '')
    if status == 'SUBMITTED RESPONDENT':
        counts[kab]['completed'] += 1
        
        mod_date_str = d.get('dateModified')
        if mod_date_str:
            mod_date = datetime.datetime.fromisoformat(mod_date_str.replace('Z', '+00:00')).date()
            if mod_date == today:
                counts[kab]['today'] += 1
            elif mod_date == today - datetime.timedelta(days=1):
                counts[kab]['yesterday'] += 1

for kab, c in counts.items():
    print(f"{kab}: Total={c['total']}, Completed={c['completed']}, Today={c['today']}, Yesterday={c['yesterday']}")
